function resolveTime(d, to, from){
    var route = d.bus_route.split(" - ")
    var a = route.indexOf(to)
    return 
    "bus_route\":\"THIRUVANANTHAPURAM (TVM) - VENJARAMOODU (VJD) - KILIMANOOR (KMR) - CHADAYAMANGALAM (CDM) - AYOOR - KOTTARAKKARA BS (KTR) - ADOOR BS (ADR) - PANDALAM (PDM) - CHENGANNUR BS (CGR) - THIRUVALLA BS (TVL) - CHANGANASSERY BS (CHR) - KOTTAYAM BS (KTM) - ETTUMANOOR - KOOTHATTUKULAM (KKM) - MUVATTUPUZHA (MVP) - PERUMBAVOOR BS (PBR) - ANKAMALY (ANK) - CHALAKUDY BS (CLD) - PUTHUKKAD (PDK) - THRISSUR BS (TSR) - KUNNAMKULAM - EDAPPAL - KUTTIPPURAM - VALANCHERY - KOTTAKKAL - UNIVERSITY (CALICUT) - KOZHIKKODE (KKD)\
    
    
}
